sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t sambachennamsetty/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sambachennamsetty/docker-react npm run test

deploy:
  provider: elastickbeanstalk
  region: "us-east-2"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-us-east-2-533267167738"
  bucket_path: "frontend"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"