sudo: required
services:
  - docker

before_install:
  - docker build -t sambachennamsetty/docker-react -f Dockerfile.dev .

script:
  - docker run sambachennamsetty/docker-react npm run test -- --coverage
